export type {
  EntityId,
  PropertyPath,
  VariableName,
  Primitive,
  ValueRef,
  Expression,
  Value,
  Vec2,
  Vec3,
  Position,
  Transform,
  Color,
  StrokeStyle,
  Gradient,
  GradientStop,
  PropertyAnim,
  PropertyInteract,
  CursorStyle,
  Prop,
  PropertyBag,
  Keyframe,
  EasingFunction,
  AnimationBinding,
  TimelineStep,
  Timeline,
  InteractionEvent,
  InteractionEventType,
  InteractionAction,
  SetPropertyAction,
  ToggleAction,
  ShowTooltipAction,
  EmitAction,
  EntityType,
  Entity,
  RelationshipType,
  Relationship,
  SceneMeta,
  Scene,
  Viewport,
  Camera,
} from './types.js'

export { validateScene, isScene } from './validate.js'
export type { ValidationResult, ValidationError } from './validate.js'
